const DOMPURIFY_CONFIG = {
  FORBID_TAGS: [
    "script",
    "style",
    "iframe",
    "object",
    "embed",
    "form",
    "button",
    "select",
    "textarea",
    "base",
    "link",
    "meta",
    "noscript",
    "template",
  ],
  FORBID_ATTR: [
    "onerror",
    "onload",
    "onclick",
    "onmouseover",
    "onmouseout",
    "onmouseenter",
    "onmouseleave",
    "onfocus",
    "onblur",
    "onchange",
    "oninput",
    "onsubmit",
    "onreset",
    "onkeydown",
    "onkeyup",
    "onkeypress",
    "oncontextmenu",
    "ondblclick",
    "ondrag",
    "ondrop",
    "style",
    "formaction",
    "srcdoc",
    "xlink:href",
  ],
  ALLOW_ONLY_SAFE_URI_ATTRIBUTES: true,
  FORCE_BODY: true,
  ALLOWED_URI_REGEXP:
    /^(?:(?:https|appimg):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
};

const KATEX_MACROS = {
  "\\R": "\\mathbb{R}",
  "\\N": "\\mathbb{N}",
  "\\Z": "\\mathbb{Z}",
  "\\Q": "\\mathbb{Q}",
  "\\C": "\\mathbb{C}",
  "\\P": "\\mathbb{P}",
  "\\E": "\\mathbb{E}",
  "\\Var": "\\operatorname{Var}",
  "\\Cov": "\\operatorname{Cov}",
  "\\Prob": "\\operatorname{P}",
  "\\dd": "\\,\\mathrm{d}",
  "\\dx": "\\,\\mathrm{d}x",
  "\\dy": "\\,\\mathrm{d}y",
  "\\dz": "\\,\\mathrm{d}z",
  "\\abs": "\\left|#1\\right|",
  "\\norm": "\\left\\lVert#1\\right\\rVert",
  "\\set": "\\left\\{#1\\right\\}",
};

const SHARED_KATEX_OPTIONS = {
  strict: "ignore" as const,
  maxExpand: 500,
  maxSize: 12,
  throwOnError: false,
  macros: { ...KATEX_MACROS },
};

export { DOMPURIFY_CONFIG, KATEX_MACROS, SHARED_KATEX_OPTIONS };
