const IPC_CHANNELS = {
  // electron api
  SHOW_CONTEXT_MENU: "electron:show-context-menu",
  OPEN_EXTERNAL: "electron:open-external",
  OPEN_DEFAULT_EDITOR: "electron:open-default-editor",
  OPEN_AUTO_EXPORT_FOLDER: "electron:open-auto-export-folder",
  GET_AUTO_EXPORT_PATH: "electron:get-auto-export-path",
  OPEN_APP_PATH: "electron:open-app-path",
  SET_THEME: "electron:set-theme",
  APP_PIN: "electron:app-pin",
  SHOW_NOTIFICATION: "electron:show-notification",
  WRITE_IMAGE: "electron:write-image",
  // settings api
  APP_ZOOM: "setting:app-zoom",
  GET_SETTING: "setting:get-setting",
  GET_ALL_SETTINGS: "setting:get-all-settings",
  SET_SETTING: "setting:set-setting",
  // note api
  GET_ALL_NOTES: "note:get-all-notes",
  GET_ALL_NOTES_BACKUP: "note:get-all-notes-backup",
  NOTE_SEARCH: "note:note-search",
  NOTE_CREATE: "note:note-create",
  NOTE_CREATE_MANY: "note:note-create-many",
  NOTE_UPDATE: "note:note-update",
  NOTE_UPDATE_FLUSH: "note:note-update-flush",
  NOTE_DELETE: "note:note-delete",
  NOTE_DELETE_MANY: "note:note-delete-many",
  NOTE_GET_BY_ID: "note:note-get-by-id",
  NOTE_GET_MANY_BY_ID: "note:note-get-many-by-id",
  SELECT_AUTO_EXPORT_FOLDER: "note:select-auto-export-folder",
  NOTE_SYNC: "note:note-sync",
  NOTE_IMPORT: "note:note-import",
  NOTE_EXPORT: "note:note-export",
  NOTE_EXPORT_MANY: "note:note-export-many",
  NOTE_PIN: "note:note-pin",
  NOTE_PIN_MANY: "note:note-pin-many",
  DB_BACKUP: "note:db-backup",
  DB_BACKUP_RESTORE: "note:db-backup-restore",
  // callbacks
  THEME_CHANGED: "callback:theme-changed",
  TRIGGER_TABLE_ACTION: "callback:trigger-table-action",
  TRIGGER_NOTE_ITEM_ACTION: "callback:trigger-note-item-action",
  TRIGGER_EXPORT: "callback:trigger-export",
  TRIGGER_SHOW_IN_FOLDER: "callback:trigger-show-in-folder",
  TRIGGER_OPEN_DEFAULT_EDITOR: "callback:trigger-open-default-editor",
  TRIGGER_COPY_RICH_TEXT: "callback:trigger-copy-rich-text",
  TRIGGER_COPY_PATH: "callback:trigger-copy-path",
  TRIGGER_DELETE: "callback:trigger-delete",
  TRIGGER_DUPLICATE: "callback:trigger-duplicate",
  TRIGGER_PIN: "callback:trigger-pin",
  TRIGGER_SELECT: "callback:trigger-select",
  TRIGGER_SYNC: "callback:trigger-sync",
  REQUEST_FLUSH: "callback:request-flush",
  // messages
  CONFIRM_FLUSH: "message:confirm-flush",
  SET_ACTIVE_NOTE: "message:set-active-note",
} as const;

export { IPC_CHANNELS };
